### ISSUE TITLE
.tmx files usefulness

### ISSUE THREAD

**Issue by MisterDev** [loopingdoge/mesopotamia-jones#12]
We have [this](https://github.com/loopingdoge/mesopotamia-jones/tree/master/assets/mapeditor) folder full of `.tmx` tilemaps exported by Tiled but we only use [these](https://github.com/loopingdoge/mesopotamia-jones/tree/master/assets/tilemaps) `.json` tilemaps.
Also, I can't see any difference between `.tmx` and `.json` opening them using Tiled.

Is there a reason to keep both files types?

**Comment by illbexyz** [comment]
I didn't know Tiled can open `.json` files, we can delete the .tmx!
