### ISSUE TITLE
Riddle text-block correspondence

### ISSUE THREAD

**Issue by illbexyz** [loopingdoge/mesopotamia-jones#14]
It could not be very clear the correspondence between the numbers in the riddle text and the blocks "numeroX".
![image](https://user-images.githubusercontent.com/3688366/30759381-4b7e8402-9fd6-11e7-908b-9722bfdaf2c3.png)

We could differentiate the colors of each variable in order to create a correspondence between the letters and the blocks.

**Comment by MisterDev** [comment]
I think this has been improved using the new `RIDDLE_PARAMS` statement:

<img width="991" alt="screen shot 2017-10-02 at 16 26 06" src="https://user-images.githubusercontent.com/11232797/31082158-6ac3e3e2-a78e-11e7-8bad-e932b8cadf93.png">

<img width="970" alt="screen shot 2017-10-02 at 16 23 42" src="https://user-images.githubusercontent.com/11232797/31082073-26a3a0bc-a78e-11e7-9ab9-1290a989eb2b.png">
