### ISSUE TITLE
Blockly Editor sfasa

### ISSUE THREAD

**Issue by MisterDev** [loopingdoge/mesopotamia-jones#2]
Non si riescono piu' a draggare i blocchi decentemente:

- Le prime 3 volte che si dragga un blocco nel workspace, quando lo si rilascia si sposta
- Quando si prende un nuovo bloccoo dalla toolbox viene rilasciato automaticamente 

Mi ricordo che successe schifo simile quando ci lavoravo anche io :D ma non ricordo why

**Comment by illbexyz** [comment]
Prima dei tuoi commit non lo faceva, quindi boh, e' qualcosa che hai messo tu a dargli fastidio

**Comment by MisterDev** [comment]
Tu hai lo stesso problema ora?
