### ISSUE TITLE
Come rappresentare i parametri

### ISSUE THREAD

**Issue by MisterDev** [loopingdoge/mesopotamia-jones#3]
1. E' piu in linguaggio naturale, poco scalabile (se servisse un array?) e un po' e' bruttino
<img width="305" alt="screen shot 2017-07-26 at 23 05 49" src="https://user-images.githubusercontent.com/11232797/28643815-63b61bcc-7257-11e7-9deb-d00143f51958.png">

2. Mettendoli non movable/deletable/editable come blocchi a parte nel workspace. Non so come funzioni la codegeneration 
<img width="203" alt="screen shot 2017-07-26 at 23 11 03" src="https://user-images.githubusercontent.com/11232797/28643919-b94d9592-7257-11e7-9b70-140ce620a4f5.png">

@illbexyz

**Comment by illbexyz** [comment]
La 2 credo che sia piu' comoda e bella da vedere
