### ISSUE TITLE
[a e s t h e t i c] Riddle screen

### ISSUE THREAD

**Issue by illbexyz** [loopingdoge/mesopotamia-jones#6]
- The beige/orange colors are okay with theme of the game (and with doge's colors too!), but the current color selection is awful.
- Every button needs a pimp up.
- Furthermore, we should try to blend together the riddle screen's colors with the toolbox ones.

**Comment by MisterDev** [comment]
Totally agree, but... why this 'tag' `[a e s t h e t i c]`?

**Comment by illbexyz** [comment]
http://knowyourmeme.com/memes/aesthetic
