### ISSUE TITLE
Blockly run code button

### ISSUE THREAD

**Issue by illbexyz** [loopingdoge/mesopotamia-jones#8]
Currently the run code button is inside the Riddle component, but I think we should create a component which contains both the blockly editor and the button.

Also, we should make the button prettier.

**Comment by MisterDev** [comment]
This is how the "Run code" button is in my mind, style and animations should be improved.

<img width="555" alt="screen shot 2017-09-05 at 21 34 15" src="https://user-images.githubusercontent.com/11232797/30079892-0680b354-9282-11e7-8952-496991920806.png">

Do you have something different in mind?

**Comment by illbexyz** [comment]
Looks good to me!
