### ISSUE TITLE
Interactive map usefulness

### ISSUE THREAD

**Issue by illbexyz** [loopingdoge/mesopotamia-jones#9]
Is the interactive map a good idea? I mean, while it's cool that a user can remotely hack a door, is he ever going to do that?

The only scenario I can think about is when a user wants to see how he solved a previous riddle without going all the way back to that door. But even in this scenario I don't see why he should change his solution.

**Comment by MisterDev** [comment]
It is useful to test how knowledge acquired while playing could be used to improve previous riddles solutions. As you said, I think nobody would ever do that unless we force them to. 

We can keep the map with the solutions while preventing any edit.
